language: java
jdk:
- openjdk9
services:
- mongodb
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: 382e5214-25db-4d1f-827a-4f67ce4f408c
  app: springbootback
  on:
    repo: Jonathans0ramirez/SpringBoot
