language: java
jdk:
- openjdk9
services:
- mongodb
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API
  app: SpringBoot
  on:
    repo: Jonathans0ramirez/SpringBoot
